### ISSUE TITLE
Can't install in Laravel 7

### ISSUE THREAD

**Issue by mtamagusku** [DarkaOnLine/L5-Swagger#303] opened 2020-08-04 19:47 UTC
- L5-Swagger Version: #.#.# (`composer show | grep l5-swagger`)
- PHP Version (`php -v`): 7.4.7
- OS: 

### Steps To Reproduce:
I do  composer require darkaonline/l5-swagger --prefer-dist, and then have this error.

Using version ^7.0 for darkaonline/l5-swagger
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 5 installs, 0 updates, 0 removals
  - Installing symfony/yaml (v5.1.3): Loading from cache
  - Installing swagger-api/swagger-ui (v3.31.1): Loading from cache
  - Installing doctrine/annotations (1.10.3): Loading from cache
  - Installing zircote/swagger-php (3.0.4): Loading from cache
  - Installing darkaonline/l5-swagger (7.0): Loading from cache
darkaonline/l5-swagger suggests installing zircote/swagger-php:~2.0 (!!! Require Swagger-PHP ~2.0 for @SWG annotations support !!!)
Writing lock file
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

   TypeError

  Argument 2 passed to L5Swagger\Generator::__construct() must be of the type string, null given, called in C:\xampp\htdocs\api_rest_ab\vendor\darkaonline\l5-swagger\src\L5SwaggerServiceProvider.php on line 66

  at C:\xampp\htdocs\proyect\vendor\darkaonline\l5-swagger\src\Generator.php:62
    58|      * @var string
    59|      */
    60|     protected $swaggerVersion;
    61|
  > 62|     public function __construct(
    63|         $annotationsDir,
    64|         string $docDir,
    65|         string $docsFile,
    66|         string $yamlDocsFile,

  1   C:\xampp\htdocs\proyect\vendor\darkaonline\l5-swagger\src\L5SwaggerServiceProvider.php:66
      L5Swagger\Generator::__construct("/api-docs.json", "/api-docs.yaml", [])

  2   C:\xampp\htdocs\proyect\vendor\laravel\framework\src\Illuminate\Container\Container.php:805
      L5Swagger\L5SwaggerServiceProvider::L5Swagger\{closure}(Object(Illuminate\Foundation\Application), [])
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1

Installation failed, reverting ./composer.json to its original content.

**Comment by codeyluke** [comment] 2020-08-09 15:47
Having the same issue with this as well, any updates on this?

**Comment by codeyluke** [comment] 2020-08-09 16:08
Hey, I found this solution online and it worked for me. 

https://laracasts.com/discuss/channels/laravel/installing-swagger-in-laravel-7-with-laradock


`composer remove "darkaonline/l5-swagger"
php artisan config:clear
COMPOSER_MEMORY_LIMIT=-1 composer require "darkaonline/l5-swagger"
php artisan config:cache`

I had an issue with my memory too so I i used COMPOSER_MEMORY_LIMIT.

**Comment by mtamagusku** [comment] 2020-08-10 11:19
Thank you Bro, its works.

**Comment by DarkaOnLine** [comment] 2020-08-18 10:38
Closing this as the issue is solved

**Closed by DarkaOnLine** 2020-08-18 10:38 UTC
