### ISSUE TITLE
Error Installation

### ISSUE THREAD

**Issue by ademirrocha** [DarkaOnLine/L5-Swagger#271] opened 2020-03-28 05:12 UTC
- L5-Swagger Version: 7.0 (`composer show | grep l5-swagger`)
- PHP Version (`7.4.2`):
- OS: Windows10

### Description: Composer :: TypeError
 Argument 2 passed to L5Swagger\Generator::__construct() must be of the type string, null given, called in D:\ ... \vendor\darkaonline\l5-swagger\src\L5SwaggerServiceProvider.php on line 66

**Comment by ademirrocha** [comment] 2020-03-28 05:16
![image](https://user-images.githubusercontent.com/33166918/77815462-076bc800-709a-11ea-82db-948e799fac0e.png)

**Comment by kalkin** [comment] 2020-04-02 14:10
Same issue here PHP Version `7.4.4` OS: `Gentoo GNU/Linux`

**Comment by rodrigowbazevedo** [comment] 2020-04-02 18:09
> * L5-Swagger Version: 7.0 (`composer show | grep l5-swagger`)
> * PHP Version (`7.4.2`):
> * OS: Windows10
> 
> ### Description: Composer :: TypeError
> Argument 2 passed to L5Swagger\Generator::__construct() must be of the type string, null given, called in D:\ ... \vendor\darkaonline\l5-swagger\src\L5SwaggerServiceProvider.php on line 66

Probably there's some error in your config file, or in your laravel storage path the second param of `L5Swagger\Generator::__construct()` is `string $docDir`.

These value is in your config `l5-swagger.paths.docs` the default value is:
```php
return [
    'paths' => [
        'docs' => storage_path('api-docs'),
    ]
];
```

Maybe the problem is in this function `storage_path` returning `NULL`, did you run `php artisan storage:link` ?

**Comment by fey** [comment] 2020-04-12 11:21
Same issue, `7.4.4` `Ubuntu 18.04`

After installation, we dont have config file, so 
`$ php artisan vendor:publish --provider "L5Swagger\L5SwaggerServiceProvider"`
throw  same error.

**Comment by fey** [comment] 2020-04-12 11:53
I think, problem is config cache

**Comment by luctop** [comment] 2020-04-14 07:37
doing php artisan config:clear fixed this issue for me

**Comment by gierg** [comment] 2020-04-14 19:20
> doing php artisan config:clear fixed this issue for me

after what?
I doesn't run command `php artisan config:clear` after `composer install`, that issue still show, please give full instruction, don't absurd like that.

**Comment by gierg** [comment] 2020-04-14 19:26
> Same issue here PHP Version `7.4.4` OS: `Gentoo GNU/Linux`
 me too...

this is my composer

`"require": {
        "php": "^7.2.5",
        "doctrine/dbal": "~2.3",
        "fideloper/proxy": "^4.2",
        "fruitcake/laravel-cors": "^1.0",
        "guzzlehttp/guzzle": "^6.3",
        "infyomlabs/coreui-templates": "7.0.x-dev",
        "infyomlabs/laravel-generator": "7.0.x-dev",
        "laravel/framework": "^7.0",
        "laravel/passport": "^8.4",
        "laravel/tinker": "^2.0",
        "laravel/ui": "^2.0",
        "laravelcollective/html": "^6.1",
        "spatie/laravel-permission": "^3.11"
    },
    "require-dev": {
        "facade/ignition": "^2.0",
        "fzaninotto/faker": "^1.9.1",
        "mockery/mockery": "^1.3.1",
        "nunomaduro/collision": "^4.1",
        "phpunit/phpunit": "^8.5",
        "darkaonline/l5-swagger": "^7.0",
        "zircote/swagger-php": "^3.0"
    },`

**Comment by rodrigowbazevedo** [comment] 2020-04-14 19:57
Can you try to run and see the return of this two commands:
```php
dd(storage_path('api-docs'));
```
and 
```php
dd(config('l5-swagger.paths.docs'));
```
They'll probably have the same response, it seems that the problem is that they are returning `null`, but they need to return something like 'storage/api-docs', I don't know why but maybe your storage path don't have the right permissions.

**Comment by gierg** [comment] 2020-04-15 04:18
> Can you try to run and see the return of this two commands:
> 
> ```
> dd(storage_path('api-docs'));
> ```
> 
> and
> 
> ```
> dd(config('l5-swagger.paths.docs'));
> ```
> 
> They'll probably have the same response, it seems that the problem is that they are returning `null`, but they need to return something like 'storage/api-docs', I don't know why but maybe your storage path don't have the right permissions.

this is my return `..\storage\api-docs`

**Comment by rodrigowbazevedo** [comment] 2020-04-15 04:27
> > Can you try to run and see the return of this two commands:
> > ```
> > dd(storage_path('api-docs'));
> > ```
> > 
> > 
> > and
> > ```
> > dd(config('l5-swagger.paths.docs'));
> > ```
> > 
> > 
> > They'll probably have the same response, it seems that the problem is that they are returning `null`, but they need to return something like 'storage/api-docs', I don't know why but maybe your storage path don't have the right permissions.
> 
> this is my return `..\storage\api-docs`

And you are having exactly the same error  as @ademirrocha ?

Can you paste it here?

**Comment by rodrigowbazevedo** [comment] 2020-04-15 04:35
Ohhhh I think I understood now... Maybe the problem is the Windows `\`

The library is concatenating with the Unix `/`.
```php
$docDir = config('l5-swagger.paths.docs');
$docsFile = $docDir .'/'. config('l5-swagger.paths.docs_json', 'api-docs.json');
$yamlDocsFile = $docDir .'/'. config('l5-swagger.paths.docs_yaml', 'api-docs.yaml');
```

Replace the Unix `/` to the php const `DIRECTORY_SEPARATOR`, may fix it

```php
$docDir = config('l5-swagger.paths.docs');
$docsFile = $docDir . DIRECTORY_SEPARATOR . config('l5-swagger.paths.docs_json', 'api-docs.json');
$yamlDocsFile = $docDir . DIRECTORY_SEPARATOR . config('l5-swagger.paths.docs_yaml', 'api-docs.yaml');
```

**Comment by gierg** [comment] 2020-04-15 05:02
> > > Can you try to run and see the return of this two commands:
> > > ```
> > > dd(storage_path('api-docs'));
> > > ```
> > > 
> > > 
> > > and
> > > ```
> > > dd(config('l5-swagger.paths.docs'));
> > > ```
> > > 
> > > 
> > > They'll probably have the same response, it seems that the problem is that they are returning `null`, but they need to return something like 'storage/api-docs', I don't know why but maybe your storage path don't have the right permissions.
> > 
> > 
> > this is my return `..\storage\api-docs`
> 
> And you are having exactly the same error as @ademirrocha ?
> 
> Can you paste it here?

This is my result when install `darkaonline/l5-swagger`

`D:\..\..\root_project>composer require darkaonline/l5-swagger --dev
Using version ^7.0 for darkaonline/l5-swagger
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 5 installs, 0 updates, 0 removals
  - Installing symfony/yaml (v5.0.7): Loading from cache
  - Installing swagger-api/swagger-ui (v3.25.0): Loading from cache
  - Installing doctrine/annotations (1.10.1): Loading from cache
  - Installing zircote/swagger-php (3.0.3): Loading from cache
  - Installing darkaonline/l5-swagger (7.0): Loading from cache
darkaonline/l5-swagger suggests installing zircote/swagger-php:~2.0 (!!! Require Swagger-PHP ~2.0 for @SWG annotations support !!!)
Writing lock file
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

   TypeError

  Argument 2 passed to L5Swagger\Generator::__construct() must be of the type string, null given, called in D:\..\..\vendor\darkaonline\l5-swagger\src\L5SwaggerServiceProvider.php on line 74

  at D:\..\..\vendor\darkaonline\l5-swagger\src\Generator.php:62
    58|      * @var string
    59|      */
    60|     protected $swaggerVersion;
    61|
  > 62|     public function __construct(
    63|         $annotationsDir,
    64|         string $docDir,
    65|         string $docsFile,
    66|         string $yamlDocsFile,

  1   D:\..\..\vendor\darkaonline\l5-swagger\src\L5SwaggerServiceProvider.php:74
      L5Swagger\Generator::__construct("/api-docs.json", "/api-docs.yaml", [])

  2   D:\..\..\vendor\laravel\framework\src\Illuminate\Container\Container.php:801
      L5Swagger\L5SwaggerServiceProvider::L5Swagger\{closure}(Object(Illuminate\Foundation\Application), [])
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1`

**Comment by gierg** [comment] 2020-04-15 07:08
> Ohhhh I think I understood now... Maybe the problem is the Windows `\`
> 
> The library is concatenating with the Unix `/`.
> 
> ```
> $docDir = config('l5-swagger.paths.docs');
> $docsFile = $docDir .'/'. config('l5-swagger.paths.docs_json', 'api-docs.json');
> $yamlDocsFile = $docDir .'/'. config('l5-swagger.paths.docs_yaml', 'api-docs.yaml');
> ```
> 
> Replace the Unix `/` to the php const `DIRECTORY_SEPARATOR`, may fix it
> 
> ```
> $docDir = config('l5-swagger.paths.docs');
> $docsFile = $docDir . DIRECTORY_SEPARATOR . config('l5-swagger.paths.docs_json', 'api-docs.json');
> $yamlDocsFile = $docDir . DIRECTORY_SEPARATOR . config('l5-swagger.paths.docs_yaml', 'api-docs.yaml');
> ```

always show error

`at D:\..\vendor\darkaonline\l5-swagger\src\Generator.php:62
    58|      * @var string
    59|      */
    60|     protected $swaggerVersion;
    61|
  > 62|     public function __construct(
    63|         $annotationsDir,
    64|         string $docDir,
    65|         string $docsFile,
    66|         string $yamlDocsFile,`

**Comment by christiantigre** [comment] 2020-04-15 14:11
Same Error :

php artisan config:clear

   TypeError

  Argument 2 passed to L5Swagger\Generator::__construct() must be of the type st
ring, null given, called in C:\Users\Administrador\Desktop\desarrollo\bitb
ucket\apisproject\vendor\darkaonline\l5-swagger\src\L5SwaggerServiceProvider.php
on line 66


any solutios??

**Comment by AunCly** [comment] 2020-04-15 14:47
Hello everyone, 
I have the some problem, i have fix it on deleting all files into bootstrap/cache (config/packages/routes-v7/services) and then php artisan optimize 
 Hope it help

**Comment by Hozington** [comment] 2020-04-27 18:42
Hi there,

As others have mentioned, it looks like the issue is being caused by some cache that could exist in your Laravel application.

The steps I followed to solve the problem:

1. `composer remove "darkaonline/l5-swagger"`
Remove the package to ensure that any reference to the package no longer exists. You have to do this otherwise the next command will fail.

2. `php artisan config:clear`
The above clears your config.

3. `composer require "darkaonline/l5-swagger"`
Reinstall the package. All should be well now.

**Comment by DarkaOnLine** [comment] 2020-05-07 10:44
Looks like we have a solution for this so I am closing ;)

**Closed by DarkaOnLine** 2020-05-07 10:44 UTC
