### ISSUE TITLE
Version is only available reliably for validation and serialization

### ISSUE THREAD

**Issue by ramasofficial** [DarkaOnLine/L5-Swagger#600] opened 2024-04-10 09:13 UTC
- L5-Swagger Version: #.#.# (`composer show | grep l5-swagger`)
- PHP Version (`php -v`):
- OS:

### Description:
<img width="580" alt="image" src="https://github.com/DarkaOnLine/L5-Swagger/assets/36000935/924a2601-75b4-4cfe-8cf1-17093e8b3157">

### Steps To Reproduce:
Version: 8.6.0, 8.5.2

**Comment by BernhardK91** [comment] 2024-04-11 13:57
Duplicate of https://github.com/DarkaOnLine/L5-Swagger/issues/597

**Closed** 2024-08-29 08:11 UTC
