### ISSUE TITLE
error Class \"OpenApi\\Generator\" not found

### ISSUE THREAD

**Issue by Rasoul-Karimi** [DarkaOnLine/L5-Swagger#520] opened 2023-01-19 09:43 UTC
- L5-Swagger Version: #.#.# (8.1)
- PHP Version 8.2:
- OS: Ubuntu

### Description:
 i get this error : Class \"OpenApi\\Generator\" not found
I remove the vendor directory and composer install again but not working

`exception
: 
"Error"
file
: 
"vendor/darkaonline/l5-swagger/src/Generator.php"
line
: 
176
message
: 
"Class \"OpenApi\\Generator\" not found"`

**Comment by roman-rr** [comment] 2023-01-19 17:30
Same for me after `composer update`

**Comment by Rasoul-Karimi** [comment] 2023-01-21 09:07
yes after composer update

**Comment by jangidgirish** [comment] 2023-01-24 05:38
same error after update

**Comment by mawebdev** [comment] 2023-01-24 07:33
It has to do with the package zircode/swagger-php.

darkaoline/l5-swagger requires "zircode/swagger-php where the OpenApi/Generator should be. 

For any reasons, the Generator Class isn't available in the installed version of zircode/swagger-php, which will be installed as a dependency of darkaonline/l5-swagger.

Installing the lastest 3.x version, (which is 3.3.7) of zircode/swagger-php from the projects composer.json fixes this issue as a workaround (Tested with 8.1.0):

Add this to your composer.json and run composer update:
```
"require": {
        ...,
        **"zircote/swagger-php": "3.3.7"**
    },
```

**Comment by DerManoMann** [comment] 2023-01-24 07:53
Good answer. Looks like a bug here as L5 only requires `^3` which obviously is wrong.

**Comment by CleisonPaiva** [comment] 2023-01-24 12:37
> It has to do with the package zircode/swagger-php.
> 
> darkaoline/l5-swagger requires "zircode/swagger-php where the OpenApi/Generator should be.
> 
> For any reasons, the Generator Class isn't available in the installed version of zircode/swagger-php, which will be installed as a dependency of darkaonline/l5-swagger.
> 
> Installing the lastest 3.x version, (which is 3.3.7) of zircode/swagger-php from the projects composer.json fixes this issue as a workaround (Tested with 8.1.0):
> 
> Add this to your composer.json and run composer update:
> 
> ```
> "require": {
>         ...,
>         "zircote/swagger-php": "3.3.7"
>     },
> ```

it worked for me

**Comment by Rasoul-Karimi** [comment] 2023-02-22 07:05
please update the package and release fixed version @collegeman @DarkaOnLine @verwilst @StyleCIBot @ashish-khokhar
@rlems @ymhuang0808 @rodrigowbazevedo @firdaushatta

**Comment by DarkaOnLine** [comment] 2023-02-22 07:43
@Rasoul-Karimi what is wrong with package requirements? We have `swagger-php: "^3.2.0 || ^4.0.0"`

https://github.com/DarkaOnLine/L5-Swagger/blob/master/composer.json#L24

**Comment by Rasoul-Karimi** [comment] 2023-02-22 07:58
@DarkaOnLine
after update i get new error!! now i have too many document and work file with version 8.1 but after update to 8.5 get this error:

Required @OA\Info() not found

 i done need to get new error! :) i wnat to only fix this one: error Class \"OpenApi\\Generator\" not found

**Comment by DarkaOnLine** [comment] 2023-02-22 08:36
Have you check this for `@OA\Info()` problem: https://zircote.github.io/swagger-php/guide/faq.html#warning-required-oa-info-not-found

**Comment by GalinaBublik** [comment] 2023-04-05 06:36
Installed "darkaonline/l5-swagger": "8.1", because latest version 8.5 - return "Required https://github.com/OA\Info() not found"
BUT i have 
`
/**
 * @OA\Info(
 *     title="OnePlusOne Solutions API",
 *     version="1.0.0"
 * )
 */
`
in my class Controller!!!
Done composer require "zircote/swagger-php:3.*" - nothing changed (((

**Comment by Outsidaz** [comment] 2023-04-13 11:21
I can confirm, that after adding the downgraded swagger-php 3.x version to composer.json everything works fine:
<img width="352" alt="image" src="https://user-images.githubusercontent.com/9278929/231743125-eed5d247-3942-457a-ab7b-6892b6a9b6e1.png">

PHP: 8.2.4
Laravel: 9.52.5

**Comment by sajid-deltashoppe** [comment] 2023-07-20 06:38
facing Error "Required @OA\Info() not found" its ttok my 1 day.

  at vendor\zircote\swagger-php\src\Loggers\DefaultLogger.php:31

php: 8.1.13
laravel: 10.14.1
  
![image](https://github.com/DarkaOnLine/L5-Swagger/assets/132253213/7f07e1a1-f7b9-4397-aaaf-29a6d999f1d9)

**Comment by vicanicius** [comment] 2024-03-26 13:38
> facing Error "Required @OA\Info() not found" its ttok my 1 day.
> 
> at vendor\zircote\swagger-php\src\Loggers\DefaultLogger.php:31
> 
> php: 8.1.13 laravel: 10.14.1
> 
> ![image](https://private-user-images.githubusercontent.com/132253213/254793817-7f07e1a1-f7b9-4397-aaaf-29a6d999f1d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzOTM3MDYsIm5iZiI6MTcxMTM5MzQwNiwicGF0aCI6Ii8xMzIyNTMyMTMvMjU0NzkzODE3LTdmMDdlMWExLWY3YjktNDM5Ny1hYWFmLTI5YTZkOTk5ZjFkOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNVQxOTAzMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZjI3ZmJmYTVmNzEzMjQxOTI0ZmQxZGY0YzI3ZGYyZDkwOGE3YjBjZThlZTA2ZjA2M2U2M2U5ZGQ1NzQ1YTYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.IcLcC_sz-iBt7LZS7GmfkNNuV_1ZM6M8sWihSz6OnwM)

Did you solve this?

**Comment by DerManoMann** [comment] 2024-03-26 20:50
Could be this one: https://zircote.github.io/swagger-php/guide/faq.html#warning-required-oa-info-not-found

**Closed** 2024-08-29 08:18 UTC
