### ISSUE TITLE
Problem in generating api-docs.json file

### ISSUE THREAD

**Issue by nastoychev** [DarkaOnLine/L5-Swagger#214] opened 2019-07-18 19:01 UTC
- L5-Swagger Version: (`5.8.1`)
- PHP Version (`7.1.30`):
- OS: Ubuntu 18.04.2 LTS
- Vagrant Version (`2.2.5`)
- Homestead Version (`9.0.3`)
- Homestead Vagrant Box (`8.0.0`)
### Description:
When i open the page (http://api.xxxxx.local/api/documentation?pw=swagger) does not generate .json file and i receive the following page:
![SharedScreenshot](https://user-images.githubusercontent.com/41673191/61483414-07f58000-a99d-11e9-970d-6dde59111149.jpg)

When i try after that to generate api-docs.json, i recive:
![SharedScreenshot2](https://user-images.githubusercontent.com/41673191/61483694-ad105880-a99d-11e9-973d-d06f4e28fc84.jpg)
 
When i delete the Storage/api-docs and try to generate again, **it works**. 
But evry time we must delete it manuell.

I found a solution to save the situation: 
vendor\darkaonline\l5-swagger\src\Generator.php: 84 

**From:**

 `
// delete all existing documentation
        if (File::exists($this->docDir)) {
            File::deleteDirectory($this->docDir);
        }
`

**TO:**

 `        // delete all existing documentation
        if (File::exists($this->docDir)) {
            File::cleanDirectory($this->docDir);
			Storage::deleteDirectory($this->docDir);
			rmdir($this->docDir);
        }`
and then when we write:

` php artisan l5-swagger:generate`

It works, but I'm not sure if this is the right way.

**Comment by ian-nisbet** [comment] 2019-08-15 09:01
This is a new issue that occurs in 5.8.1 I was able to debug my swagger php docs by changing the composer dependency to "darkaonline/l5-swagger": "5.8.0", then composer update.
Now the bugs are sent as exceptions to the browser.
It appears that 5.8.1 is catching the exceptions, but not logging them.

**Comment by DarkaOnLine** [comment] 2019-08-30 07:04
Hmm, it looks strange. `File::deleteDirectory($this->docDir);` should delete all files in directory and directory itself. Do you have correct permissions for files and directory?

**Comment by SkyCrew-g** [comment] 2019-09-13 08:13
Yes, I have the rights necessary to remove and edit.

**Comment by marija-bogdanovic** [comment] 2019-11-27 12:22
The same problem here too.

**Comment by Fahd-Ibtikar** [comment] 2019-12-08 14:33
Same problem here.

**Comment by SkyCrew-g** [comment] 2019-12-11 15:51
The problem is resolved via:  sudo update-alternatives --config php and i choosed 7.3 ver. for php-cli

**Comment by mustafadahab** [comment] 2019-12-29 12:36
To fix the issue you need to use 
"zircote/swagger-php": "3.*"
Not 
"zircote/swagger-php": "2.*"

**Comment by SkyCrew-g** [comment] 2020-01-02 09:03
Yes it can be a solution, but when you need the old Antonations, then you should use zircote v2. I already written my solution.

**Comment by SkyCrew-g** [comment] 2020-01-02 09:03
> To fix the issue you need to use
> "zircote/swagger-php": "3._" Not "zircote/swagger-php": "2._"

Yes it can be a solution, but when you need the old Antonations, then you should use zircote v2. I already written my solution.

**Comment by ShynHan** [comment] 2020-04-09 05:31
edit this file “vendor/darkaonline/l5-swagger/src/Generator.php” about 83~87line
```php
        // delete all existing documentation
        if (File::exists($this->docDir)) {
            File::deleteDirectory($this->docDir);
            @rmdir($this->docDir); // add this new line
        }
```

**Comment by ShynHan** [comment] 2020-04-09 05:31
edit this file “vendor/darkaonline/l5-swagger/src/Generator.php” about 83~87line

```php
        // delete all existing documentation
        if (File::exists($this->docDir)) {
            File::deleteDirectory($this->docDir);
            @rmdir($this->docDir); // add this new line
        }
```

**Comment by experteam-mx** [comment] 2021-10-12 18:36
Same problem here.

**Closed** 2022-03-04 12:03 UTC

**Comment by DarkaOnLine** [comment] 2022-04-27 07:38
Closing due to no activity for a very long time

**Comment by origamiv** [comment] 2023-06-08 04:17
Same problem here.
